# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stuart/Projects/Qt/Basic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stuart/Projects/Qt/Basic/build

# Include any dependencies generated for this target.
include CMakeFiles/textEditor.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/textEditor.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/textEditor.dir/flags.make

CMakeFiles/textEditor.dir/textEditor_automoc.o: CMakeFiles/textEditor.dir/flags.make
CMakeFiles/textEditor.dir/textEditor_automoc.o: textEditor_automoc.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/stuart/Projects/Qt/Basic/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/textEditor.dir/textEditor_automoc.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/textEditor.dir/textEditor_automoc.o -c /home/stuart/Projects/Qt/Basic/build/textEditor_automoc.cpp

CMakeFiles/textEditor.dir/textEditor_automoc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/textEditor.dir/textEditor_automoc.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/stuart/Projects/Qt/Basic/build/textEditor_automoc.cpp > CMakeFiles/textEditor.dir/textEditor_automoc.i

CMakeFiles/textEditor.dir/textEditor_automoc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/textEditor.dir/textEditor_automoc.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/stuart/Projects/Qt/Basic/build/textEditor_automoc.cpp -o CMakeFiles/textEditor.dir/textEditor_automoc.s

CMakeFiles/textEditor.dir/textEditor_automoc.o.requires:
.PHONY : CMakeFiles/textEditor.dir/textEditor_automoc.o.requires

CMakeFiles/textEditor.dir/textEditor_automoc.o.provides: CMakeFiles/textEditor.dir/textEditor_automoc.o.requires
	$(MAKE) -f CMakeFiles/textEditor.dir/build.make CMakeFiles/textEditor.dir/textEditor_automoc.o.provides.build
.PHONY : CMakeFiles/textEditor.dir/textEditor_automoc.o.provides

CMakeFiles/textEditor.dir/textEditor_automoc.o.provides.build: CMakeFiles/textEditor.dir/textEditor_automoc.o
.PHONY : CMakeFiles/textEditor.dir/textEditor_automoc.o.provides.build

CMakeFiles/textEditor.dir/main.o: CMakeFiles/textEditor.dir/flags.make
CMakeFiles/textEditor.dir/main.o: ../main.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/stuart/Projects/Qt/Basic/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/textEditor.dir/main.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/textEditor.dir/main.o -c /home/stuart/Projects/Qt/Basic/main.cpp

CMakeFiles/textEditor.dir/main.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/textEditor.dir/main.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/stuart/Projects/Qt/Basic/main.cpp > CMakeFiles/textEditor.dir/main.i

CMakeFiles/textEditor.dir/main.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/textEditor.dir/main.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/stuart/Projects/Qt/Basic/main.cpp -o CMakeFiles/textEditor.dir/main.s

CMakeFiles/textEditor.dir/main.o.requires:
.PHONY : CMakeFiles/textEditor.dir/main.o.requires

CMakeFiles/textEditor.dir/main.o.provides: CMakeFiles/textEditor.dir/main.o.requires
	$(MAKE) -f CMakeFiles/textEditor.dir/build.make CMakeFiles/textEditor.dir/main.o.provides.build
.PHONY : CMakeFiles/textEditor.dir/main.o.provides

CMakeFiles/textEditor.dir/main.o.provides.build: CMakeFiles/textEditor.dir/main.o
.PHONY : CMakeFiles/textEditor.dir/main.o.provides.build

CMakeFiles/textEditor.dir/mainwindow.o: CMakeFiles/textEditor.dir/flags.make
CMakeFiles/textEditor.dir/mainwindow.o: ../mainwindow.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/stuart/Projects/Qt/Basic/build/CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/textEditor.dir/mainwindow.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/textEditor.dir/mainwindow.o -c /home/stuart/Projects/Qt/Basic/mainwindow.cpp

CMakeFiles/textEditor.dir/mainwindow.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/textEditor.dir/mainwindow.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/stuart/Projects/Qt/Basic/mainwindow.cpp > CMakeFiles/textEditor.dir/mainwindow.i

CMakeFiles/textEditor.dir/mainwindow.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/textEditor.dir/mainwindow.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/stuart/Projects/Qt/Basic/mainwindow.cpp -o CMakeFiles/textEditor.dir/mainwindow.s

CMakeFiles/textEditor.dir/mainwindow.o.requires:
.PHONY : CMakeFiles/textEditor.dir/mainwindow.o.requires

CMakeFiles/textEditor.dir/mainwindow.o.provides: CMakeFiles/textEditor.dir/mainwindow.o.requires
	$(MAKE) -f CMakeFiles/textEditor.dir/build.make CMakeFiles/textEditor.dir/mainwindow.o.provides.build
.PHONY : CMakeFiles/textEditor.dir/mainwindow.o.provides

CMakeFiles/textEditor.dir/mainwindow.o.provides.build: CMakeFiles/textEditor.dir/mainwindow.o
.PHONY : CMakeFiles/textEditor.dir/mainwindow.o.provides.build

# Object files for target textEditor
textEditor_OBJECTS = \
"CMakeFiles/textEditor.dir/textEditor_automoc.o" \
"CMakeFiles/textEditor.dir/main.o" \
"CMakeFiles/textEditor.dir/mainwindow.o"

# External object files for target textEditor
textEditor_EXTERNAL_OBJECTS =

textEditor: CMakeFiles/textEditor.dir/textEditor_automoc.o
textEditor: CMakeFiles/textEditor.dir/main.o
textEditor: CMakeFiles/textEditor.dir/mainwindow.o
textEditor: /usr/lib/libkdeui.so.5.6.0
textEditor: /usr/lib/libkdecore.so.5.6.0
textEditor: /usr/lib/libQtDBus.so
textEditor: /usr/lib/libQtCore.so
textEditor: /usr/lib/libQtGui.so
textEditor: /usr/lib/libQtSvg.so
textEditor: CMakeFiles/textEditor.dir/build.make
textEditor: CMakeFiles/textEditor.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable textEditor"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/textEditor.dir/link.txt --verbose=$(VERBOSE)
	/usr/bin/cmake -D_filename=/home/stuart/Projects/Qt/Basic/build/textEditor.shell -D_library_path_variable=LD_LIBRARY_PATH -D_ld_library_path="/home/stuart/Projects/Qt/Basic/build/lib/./:/usr/local/lib:/usr/lib:/usr/lib" -D_executable=/home/stuart/Projects/Qt/Basic/build/textEditor -P /usr/share/kde4/apps/cmake/modules/kde4_exec_via_sh.cmake

# Rule to build all files generated by this target.
CMakeFiles/textEditor.dir/build: textEditor
.PHONY : CMakeFiles/textEditor.dir/build

CMakeFiles/textEditor.dir/requires: CMakeFiles/textEditor.dir/textEditor_automoc.o.requires
CMakeFiles/textEditor.dir/requires: CMakeFiles/textEditor.dir/main.o.requires
CMakeFiles/textEditor.dir/requires: CMakeFiles/textEditor.dir/mainwindow.o.requires
.PHONY : CMakeFiles/textEditor.dir/requires

CMakeFiles/textEditor.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/textEditor.dir/cmake_clean.cmake
.PHONY : CMakeFiles/textEditor.dir/clean

CMakeFiles/textEditor.dir/depend:
	cd /home/stuart/Projects/Qt/Basic/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/stuart/Projects/Qt/Basic /home/stuart/Projects/Qt/Basic /home/stuart/Projects/Qt/Basic/build /home/stuart/Projects/Qt/Basic/build /home/stuart/Projects/Qt/Basic/build/CMakeFiles/textEditor.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/textEditor.dir/depend

